### ISSUE TITLE
TypeError: Accelerator.__init__() got an unexpected keyword argument 'use_seedable_sampler'

### ISSUE THREAD

**Issue by SrikanthChellappa** [Victorwz/LLaVA-Llama-3#5]
Traceback (most recent call last):
  File "/home/srikanth/api-webapp/LLaVA-Llama-3/llava/train/train_mem.py", line 4, in <module>
    train(attn_implementation="flash_attention_2")
  File "/home/srikanth/api-webapp/LLaVA-Llama-3/llava/train/train.py", line 1172, in train
    trainer = LLaVATrainer(model=model,
  File "/home/srikanth/.local/lib/python3.10/site-packages/transformers/trainer.py", line 402, in __init__
    self.create_accelerator_and_postprocess()
  File "/home/srikanth/.local/lib/python3.10/site-packages/transformers/trainer.py", line 4535, in create_accelerator_and_postprocess
    self.accelerator = Accelerator(**args)
TypeError: Accelerator.__init__() got an unexpected keyword argument 'use_seedable_sampler'

*************************************************************************
This is the below script used for finetuning

deepspeed --num_gpus=1 llava/train/train_mem.py \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \
    --deepspeed /home/srikanth/api-webapp/LLaVA/scripts/zero3.json \
    --model_name_or_path meta-llama/Meta-Llama-3-8B-Instruct  \
    --version v3 \
    --data_path /mnt/e/Vision-Finetuning/data/llava_v1_5_mix665k.json \
    --image_folder /mnt/e/Vision-Finetuning/data/images \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --pretrain_mm_mlp_adapter /mnt/e/Generative AI/checkpoints/llava-v1.5-llama-3-8b-pretrain/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir /mnt/e/Generative AI/checkpoints/Llava-Llama-3-8B-v2-17-lora \
    --num_train_epochs 1 \
    --per_device_train_batch_size 6 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 500 \
    --max_steps 1000 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb

**Comment by SrikanthChellappa** [comment]
This got resolved after upgrading accelerate package.
